/*
File name: C:\Users\JonathanAndres\Desktop\pos.sql
Creation date: 02/08/2019
Created by MSSQL to PostgreSQL 3.3 [Demo]
--------------------------------------------------
More conversion tools at http://www.convert-in.com
*/
DO $$
BEGIN
IF NOT EXISTS (SELECT schema_name FROM information_schema.schemata WHERE schema_name = 'dbo')
THEN
CREATE SCHEMA "dbo";
END IF;
END$$;
/*
Table structure for table 'dbo.A_DATOS_FALLECIDA_O_'
*/

DROP TABLE IF EXISTS "dbo"."A_DATOS_FALLECIDA_O_" CASCADE;
CREATE TABLE "dbo"."A_DATOS_FALLECIDA_O_" (
	"ID_FALL" INTEGER NOT NULL,
	"NOM_FALL" VARCHAR(200)  NOT NULL,
	"APELL_FALL" VARCHAR(200)  NOT NULL,
	"CED_FALL" VARCHAR(200)  NOT NULL,
	"FECHANACI_FALL" TIMESTAMP NOT NULL,
	"FECHAFALL_FALL" TIMESTAMP NOT NULL,
	"NACION_FALL" VARCHAR(200)  NOT NULL,
	"ETNIA_FALL" VARCHAR(200)  NOT NULL,
	"ID_FORM" INTEGER,
	"ID_ESTADO" INTEGER,
	"ID_RESIDENCIA" INTEGER,
	"INSTRU_FALL" VARCHAR(200)  NOT NULL
) WITH OIDS;
DROP INDEX IF EXISTS "PK_A_DATOS_FALLECIDA_O_";
ALTER TABLE "dbo"."A_DATOS_FALLECIDA_O_" ADD CONSTRAINT "PK_A_DATOS_FALLECIDA_O_" PRIMARY KEY("ID_FALL");
DROP INDEX IF EXISTS "RELATIONSHIP_1_FK";
CREATE INDEX "RELATIONSHIP_1_FK" ON "dbo"."A_DATOS_FALLECIDA_O_"("ID_FORM");
DROP INDEX IF EXISTS "RELATIONSHIP_11_FK";
CREATE INDEX "RELATIONSHIP_11_FK" ON "dbo"."A_DATOS_FALLECIDA_O_"("ID_ESTADO");
DROP INDEX IF EXISTS "RELATIONSHIP_12_FK";
CREATE INDEX "RELATIONSHIP_12_FK" ON "dbo"."A_DATOS_FALLECIDA_O_"("ID_RESIDENCIA");

/*
Dumping data for table 'dbo.A_DATOS_FALLECIDA_O_'
*/

DO $$
BEGIN
IF NOT EXISTS (SELECT schema_name FROM information_schema.schemata WHERE schema_name = 'dbo')
THEN
CREATE SCHEMA "dbo";
END IF;
END$$;
/*
Table structure for table 'dbo.B_CERT_MED_DEF'
*/

DROP TABLE IF EXISTS "dbo"."B_CERT_MED_DEF" CASCADE;
CREATE TABLE "dbo"."B_CERT_MED_DEF" (
	"ID_CERT" INTEGER NOT NULL,
	"ID_FORM" INTEGER,
	"DESCRI_CERT" VARCHAR(500)  NOT NULL,
	"MORT_MAT_CERT" VARCHAR(200)  NOT NULL,
	"MUERTACCOVIOLEN_CERT" VARCHAR(200)  NOT NULL,
	"AUTOP_CERT" VARCHAR(200)  NOT NULL,
	"LUGARHECHO_CERT" VARCHAR(200)  NOT NULL
) WITH OIDS;
DROP INDEX IF EXISTS "PK_B_CERT_MED_DEF";
ALTER TABLE "dbo"."B_CERT_MED_DEF" ADD CONSTRAINT "PK_B_CERT_MED_DEF" PRIMARY KEY("ID_CERT");
DROP INDEX IF EXISTS "RELATIONSHIP_10_FK";
CREATE INDEX "RELATIONSHIP_10_FK" ON "dbo"."B_CERT_MED_DEF"("ID_FORM");

/*
Dumping data for table 'dbo.B_CERT_MED_DEF'
*/

DO $$
BEGIN
IF NOT EXISTS (SELECT schema_name FROM information_schema.schemata WHERE schema_name = 'dbo')
THEN
CREATE SCHEMA "dbo";
END IF;
END$$;
/*
Table structure for table 'dbo.C_MUERTES_SIN_CERT_MED'
*/

DROP TABLE IF EXISTS "dbo"."C_MUERTES_SIN_CERT_MED" CASCADE;
CREATE TABLE "dbo"."C_MUERTES_SIN_CERT_MED" (
	"SINTOM_MED" VARCHAR(500)  NOT NULL,
	"TEST_MED" VARCHAR(500)  NOT NULL,
	"ID_MED" INTEGER NOT NULL,
	"ID_FORM" INTEGER
) WITH OIDS;
DROP INDEX IF EXISTS "PK_C_MUERTES_SIN_CERT_MED";
ALTER TABLE "dbo"."C_MUERTES_SIN_CERT_MED" ADD CONSTRAINT "PK_C_MUERTES_SIN_CERT_MED" PRIMARY KEY("ID_MED");
DROP INDEX IF EXISTS "TIENE_FK";
CREATE INDEX "TIENE_FK" ON "dbo"."C_MUERTES_SIN_CERT_MED"("ID_FORM");

/*
Dumping data for table 'dbo.C_MUERTES_SIN_CERT_MED'
*/

DO $$
BEGIN
IF NOT EXISTS (SELECT schema_name FROM information_schema.schemata WHERE schema_name = 'dbo')
THEN
CREATE SCHEMA "dbo";
END IF;
END$$;
/*
Table structure for table 'dbo.CANTON'
*/

DROP TABLE IF EXISTS "dbo"."CANTON" CASCADE;
CREATE TABLE "dbo"."CANTON" (
	"ID_CANTON" INTEGER NOT NULL,
	"ID_LOCAL" INTEGER,
	"NOM_CANTON" VARCHAR(200)  NOT NULL
) WITH OIDS;
DROP INDEX IF EXISTS "PK_CANTON";
ALTER TABLE "dbo"."CANTON" ADD CONSTRAINT "PK_CANTON" PRIMARY KEY("ID_CANTON");
DROP INDEX IF EXISTS "RELATIONSHIP_15_FK";
CREATE INDEX "RELATIONSHIP_15_FK" ON "dbo"."CANTON"("ID_LOCAL");

/*
Dumping data for table 'dbo.CANTON'
*/

DO $$
BEGIN
IF NOT EXISTS (SELECT schema_name FROM information_schema.schemata WHERE schema_name = 'dbo')
THEN
CREATE SCHEMA "dbo";
END IF;
END$$;
/*
Table structure for table 'dbo.D_DATOS_INSCRIPCION_DEFUNCION'
*/

DROP TABLE IF EXISTS "dbo"."D_DATOS_INSCRIPCION_DEFUNCION" CASCADE;
CREATE TABLE "dbo"."D_DATOS_INSCRIPCION_DEFUNCION" (
	"CERT_INSC" VARCHAR(200)  NOT NULL,
	"QUIENCERT_INS" VARCHAR(500)  NOT NULL,
	"RELFALL_INS" VARCHAR(200)  NOT NULL,
	"DATOSQUIEN_INS" VARCHAR(500)  NOT NULL,
	"ID_INS" INTEGER NOT NULL,
	"ID_FORM" INTEGER
) WITH OIDS;
DROP INDEX IF EXISTS "PK_D_DATOS_INSCRIPCION_DEFUNCI";
ALTER TABLE "dbo"."D_DATOS_INSCRIPCION_DEFUNCION" ADD CONSTRAINT "PK_D_DATOS_INSCRIPCION_DEFUNCI" PRIMARY KEY("ID_INS");
DROP INDEX IF EXISTS "HAY_FK";
CREATE INDEX "HAY_FK" ON "dbo"."D_DATOS_INSCRIPCION_DEFUNCION"("ID_FORM");

/*
Dumping data for table 'dbo.D_DATOS_INSCRIPCION_DEFUNCION'
*/

DO $$
BEGIN
IF NOT EXISTS (SELECT schema_name FROM information_schema.schemata WHERE schema_name = 'dbo')
THEN
CREATE SCHEMA "dbo";
END IF;
END$$;
/*
Table structure for table 'dbo.EDAD_AL_FALLECER'
*/

DROP TABLE IF EXISTS "dbo"."EDAD_AL_FALLECER" CASCADE;
CREATE TABLE "dbo"."EDAD_AL_FALLECER" (
	"ID_EDAD" INTEGER NOT NULL,
	"ID_FALL" INTEGER NOT NULL,
	"HORAS_FALL" INTEGER NOT NULL,
	"DIAS_FALL" INTEGER NOT NULL,
	"MESES_FALL" INTEGER NOT NULL,
	"EDAD_FALL" INTEGER NOT NULL
) WITH OIDS;
DROP INDEX IF EXISTS "PK_EDAD_AL_FALLECER";
ALTER TABLE "dbo"."EDAD_AL_FALLECER" ADD CONSTRAINT "PK_EDAD_AL_FALLECER" PRIMARY KEY("ID_EDAD");
DROP INDEX IF EXISTS "RELATIONSHIP_7_FK";
CREATE INDEX "RELATIONSHIP_7_FK" ON "dbo"."EDAD_AL_FALLECER"("ID_FALL");

/*
Dumping data for table 'dbo.EDAD_AL_FALLECER'
*/

DO $$
BEGIN
IF NOT EXISTS (SELECT schema_name FROM information_schema.schemata WHERE schema_name = 'dbo')
THEN
CREATE SCHEMA "dbo";
END IF;
END$$;
/*
Table structure for table 'dbo.ESTADO_CIVIL'
*/

DROP TABLE IF EXISTS "dbo"."ESTADO_CIVIL" CASCADE;
CREATE TABLE "dbo"."ESTADO_CIVIL" (
	"ID_ESTADO" INTEGER NOT NULL,
	"DESC_ESTADO" VARCHAR(10)  NOT NULL
) WITH OIDS;
DROP INDEX IF EXISTS "PK_ESTADO_CIVIL";
ALTER TABLE "dbo"."ESTADO_CIVIL" ADD CONSTRAINT "PK_ESTADO_CIVIL" PRIMARY KEY("ID_ESTADO");

/*
Dumping data for table 'dbo.ESTADO_CIVIL'
*/

DO $$
BEGIN
IF NOT EXISTS (SELECT schema_name FROM information_schema.schemata WHERE schema_name = 'dbo')
THEN
CREATE SCHEMA "dbo";
END IF;
END$$;
/*
Table structure for table 'dbo.FORMULARIO'
*/

DROP TABLE IF EXISTS "dbo"."FORMULARIO" CASCADE;
CREATE TABLE "dbo"."FORMULARIO" (
	"ID_FORM" INTEGER NOT NULL,
	"OF_REG_CIV" VARCHAR(200)  NOT NULL,
	"PROV_FORM" VARCHAR(200)  NOT NULL,
	"CANT_FORM" VARCHAR(200)  NOT NULL,
	"PARR_URB_RUR_FORM" VARCHAR(200)  NOT NULL,
	"FECH_INS_FORM" TIMESTAMP NOT NULL,
	"ACTA_INS_FORM" TIMESTAMP NOT NULL
) WITH OIDS;
DROP INDEX IF EXISTS "PK_FORMULARIO";
ALTER TABLE "dbo"."FORMULARIO" ADD CONSTRAINT "PK_FORMULARIO" PRIMARY KEY("ID_FORM");

/*
Dumping data for table 'dbo.FORMULARIO'
*/

DO $$
BEGIN
IF NOT EXISTS (SELECT schema_name FROM information_schema.schemata WHERE schema_name = 'dbo')
THEN
CREATE SCHEMA "dbo";
END IF;
END$$;
/*
Table structure for table 'dbo.LOCALIDAD'
*/

DROP TABLE IF EXISTS "dbo"."LOCALIDAD" CASCADE;
CREATE TABLE "dbo"."LOCALIDAD" (
	"ID_LOCAL" INTEGER NOT NULL,
	"NOM_LOCAL" VARCHAR(200)  NOT NULL
) WITH OIDS;
DROP INDEX IF EXISTS "PK_LOCALIDAD";
ALTER TABLE "dbo"."LOCALIDAD" ADD CONSTRAINT "PK_LOCALIDAD" PRIMARY KEY("ID_LOCAL");

/*
Dumping data for table 'dbo.LOCALIDAD'
*/

DO $$
BEGIN
IF NOT EXISTS (SELECT schema_name FROM information_schema.schemata WHERE schema_name = 'dbo')
THEN
CREATE SCHEMA "dbo";
END IF;
END$$;
/*
Table structure for table 'dbo.PARROQUIA'
*/

DROP TABLE IF EXISTS "dbo"."PARROQUIA" CASCADE;
CREATE TABLE "dbo"."PARROQUIA" (
	"ID_PARR" INTEGER NOT NULL,
	"ID_LOCAL" INTEGER,
	"NOM_PARR" VARCHAR(200)  NOT NULL
) WITH OIDS;
DROP INDEX IF EXISTS "PK_PARROQUIA";
ALTER TABLE "dbo"."PARROQUIA" ADD CONSTRAINT "PK_PARROQUIA" PRIMARY KEY("ID_PARR");
DROP INDEX IF EXISTS "RELATIONSHIP_14_FK";
CREATE INDEX "RELATIONSHIP_14_FK" ON "dbo"."PARROQUIA"("ID_LOCAL");

/*
Dumping data for table 'dbo.PARROQUIA'
*/

DO $$
BEGIN
IF NOT EXISTS (SELECT schema_name FROM information_schema.schemata WHERE schema_name = 'dbo')
THEN
CREATE SCHEMA "dbo";
END IF;
END$$;
/*
Table structure for table 'dbo.PROV'
*/

DROP TABLE IF EXISTS "dbo"."PROV" CASCADE;
CREATE TABLE "dbo"."PROV" (
	"ID_PROV" INTEGER NOT NULL,
	"ID_CANTON" INTEGER,
	"NOM_PROV" VARCHAR(200)  NOT NULL
) WITH OIDS;
DROP INDEX IF EXISTS "PK_PROV";
ALTER TABLE "dbo"."PROV" ADD CONSTRAINT "PK_PROV" PRIMARY KEY("ID_PROV");
DROP INDEX IF EXISTS "RELATIONSHIP_13_FK";
CREATE INDEX "RELATIONSHIP_13_FK" ON "dbo"."PROV"("ID_CANTON");

/*
Dumping data for table 'dbo.PROV'
*/

DO $$
BEGIN
IF NOT EXISTS (SELECT schema_name FROM information_schema.schemata WHERE schema_name = 'dbo')
THEN
CREATE SCHEMA "dbo";
END IF;
END$$;
/*
Table structure for table 'dbo.RESIDENCIA'
*/

DROP TABLE IF EXISTS "dbo"."RESIDENCIA" CASCADE;
CREATE TABLE "dbo"."RESIDENCIA" (
	"ID_RESIDENCIA" INTEGER NOT NULL,
	"ID_PROV" INTEGER,
	"DIRDOM_RESI" VARCHAR(200)  NOT NULL
) WITH OIDS;
DROP INDEX IF EXISTS "PK_RESIDENCIA";
ALTER TABLE "dbo"."RESIDENCIA" ADD CONSTRAINT "PK_RESIDENCIA" PRIMARY KEY("ID_RESIDENCIA");
DROP INDEX IF EXISTS "RELATIONSHIP_9_FK";
CREATE INDEX "RELATIONSHIP_9_FK" ON "dbo"."RESIDENCIA"("ID_PROV");

/*
Dumping data for table 'dbo.RESIDENCIA'
*/

